# Generated by Django 4.2.14 on 2024-08-03 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("referral_percentage", models.FloatField(max_length=10)),
                ("is_executor", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LegalEntity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("tax_number", models.CharField(max_length=255)),
                ("legal_entity_percentage", models.FloatField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.partner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Ожидает", "Ожидает"),
                            ("Частичная отгрузка", "Частичная отгрузка"),
                            ("Готова", "Готова"),
                        ],
                        max_length=25,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("resolving_date", models.DateTimeField(null=True)),
                ("initial_sum", models.FloatField()),
                ("executor_commission", models.FloatField()),
                ("sum_with_executors_commission", models.FloatField()),
                ("commission_with_interest", models.FloatField()),
                ("uncargo_sum", models.FloatField()),
                ("referral_procentage", models.FloatField()),
                ("clean_income", models.FloatField()),
                ("comment", models.CharField(max_length=1500)),
                ("is_documents", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_customer",
                        to="main.partner",
                    ),
                ),
                (
                    "executor_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_executor",
                        to="main.partner",
                    ),
                ),
                (
                    "giving_side",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partner_giving_side",
                        to="main.partner",
                    ),
                ),
                (
                    "receiver_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_entity_receiver",
                        to="main.legalentity",
                    ),
                ),
                (
                    "sender_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legal_entity_sender",
                        to="main.legalentity",
                    ),
                ),
            ],
        ),
    ]
