# Generated by Django 4.2.14 on 2024-08-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_customuser_delete_authinformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="otp_secret_key",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
